# Kuantisasi dan verifikasi model

In [1]:
import tensorflow as tf
import numpy as np
import h5py
import matplotlib.pyplot as plt
from matplotlib.image import imread
import math
from numpy import genfromtxt

from tensorflow.keras.models import load_model,model_from_json
from tensorflow.keras.utils import CustomObjectScope
from tensorflow.keras.initializers import glorot_uniform
print("line 1 complete")

line 1 complete


# load model dari file h5

In [2]:
# Model reconstruction from JSON file
with open('model.json', 'r') as f:
    model = model_from_json(f.read())
print("model = ", model)
    
# Load weights into the new model
model.load_weights('CNN_Model.h5')
model.compile(loss="mse", optimizer="adam")
with h5py.File('CNN_Model.h5','r') as hdf:
    layer_1_data = np.array(hdf.get('layer_1/layer_1/kernel:0'))
    layer_2_data = np.array(hdf.get('layer_2/layer_2/kernel:0'))
    layer_3_data = np.array(hdf.get('layer_3/layer_3/kernel:0'))
    layer_out_data = np.array(hdf.get('layer_Output/layer_Output/kernel:0'))
    
#test check
print("test check")
print("layer 1 data = ", layer_1_data)
print("layer 2 data = ", layer_2_data)
print("layer 3 data = ", layer_3_data)
print("layer out data = ", layer_out_data)

#load dataset
(x_train, y_train),(x_test, y_test) = tf.keras.datasets.mnist.load_data()
print("line 2 complete")

model =  <tensorflow.python.keras.engine.sequential.Sequential object at 0x0000027F0D839848>
test check
layer 1 data =  [[[[-0.00843631  0.0197531   0.08764859  0.18019785 -0.0244779
     0.00047111 -0.1901128  -0.06691089 -0.09561473 -0.01535888
    -0.13130021 -0.00364014  0.04557273  0.04967131 -0.16475454
    -0.00781207]]

  [[-0.06874837  0.12709711  0.04403444 -0.04915948 -0.05648001
    -0.10971992 -0.08491378 -0.16650213 -0.08523792  0.15304513
     0.1396491  -0.18639666  0.0424715  -0.2273606  -0.14158039
     0.10024733]]

  [[ 0.11782628  0.09216962  0.02200717 -0.09428527  0.07465049
    -0.1813121  -0.12666897  0.01915183 -0.11000782 -0.12510587
     0.11462282 -0.07504352  0.07118474  0.09817253 -0.14805794
    -0.06331824]]]


 [[[ 0.1014984  -0.10333362 -0.21704143 -0.18250886 -0.11087504
     0.11706213  0.11140056 -0.0819138  -0.07083997  0.05565518
     0.02207108  0.08347375 -0.00889369 -0.11102477  0.1266945
    -0.00150051]]

  [[-0.11459075 -0.06381972 -0.16623

line 2 complete


# Fungsi - fungsi CNN

In [3]:
def pool2d(mat,ksize,method='max',pad=False):
    m, n = mat.shape[1:]
    ky,kx=ksize

    _ceil=lambda x,y: int(numpy.ceil(x/float(y)))

    if pad:
        ny=_ceil(m,ky)
        nx=_ceil(n,kx)
        size=(mat.shape[0],ny*ky, nx*kx)
        mat_pad=numpy.full(size,numpy.nan)
        mat_pad[:m,:n,...]=mat
    else:
        ny=m//ky
        nx=n//kx
        mat_pad=mat[..., :ny*ky, :nx*kx]

    new_shape=(mat.shape[0],ny,ky,nx,kx)

    if method=='max':
        result=np.nanmax(mat_pad.reshape(new_shape),axis=(2,4))
    else:
        result=np.nanmean(mat_pad.reshape(new_shape),axis=(2,4))

    return result

def channel_im2col(A):
    B = [3,3]
    skip=[1,1]
    # Parameters 
    D,M,N = A.shape
    col_extent = N - B[1] + 1
    row_extent = M - B[0] + 1

    # Get Starting block indices
    start_idx = np.arange(B[0])[:,None]*N + np.arange(B[1])

    # Generate Depth indeces
    didx=M*N*np.arange(D)
    start_idx=(didx[:,None]+start_idx.ravel()).reshape((-1,B[0],B[1]))

    # Get offsetted indices across the height and width of input array
    offset_idx = np.arange(row_extent)[:,None]*N + np.arange(col_extent)

    # Get all actual indices & index into input array for final output
    out = np.take (A,start_idx.ravel()[:,None] + offset_idx[::skip[0],::skip[1]].ravel())
    return out


def conv2d(filt,act):
    '''
    conv 2d function
    act = widht, height,depth (w1,h1,d1)
    default = 3,3 filter, stride = 1, p = 0
    im2col reshape
    
    W2=(W1−F+2P)/S+1
    H2=(H1−F+2P)/S+1
    D2=K
    '''
    P = 0
    S = 1
    D1,H1,W1 = act.shape
    n_f,d_f,h_f,w_f = filt.shape
    window_size = d_f*h_f*w_f
    filter_reshape = n_f,window_size
    W2=(W1-h_f +2*P)//S+1
    H2=(H1- h_f+2*P)//S+1
    D2= n_f
    m = channel_im2col(act)
    filt = filt.reshape(filter_reshape)
    res = np.matmul(filt, m)
    res = res.reshape(D2,W2,H2)
    return res

def softmax(X):
    expo = np.exp(X)
    expo_sum = np.sum(np.exp(X))
    return expo/expo_sum

def relu(X):
    return np.maximum(0,X)

def prequant(data,bits):
    MaxValue = np.amax(data)
    MinValue = np.amin(data)
    Range_Real = MaxValue - MinValue
    if(Range_Real==0):
        Range_Real = 1
    Scale = (Range_Real/(pow(2,bits)-1))
    return Scale, Range_Real

def quantize(Val, Range_Real, Scale, zero_point):  
    temp = round(Val * (1/Scale) + zero_point)
    return temp
quantizefunc = np.vectorize(quantize)
print("line 3 complete")

line 3 complete


In [4]:
layer_1_data = layer_1_data.transpose(3,2,0,1)
layer_2_data= layer_2_data.transpose(3,2,0,1)
print("line 4 complete")

line 4 complete


# Model Terkuantisasi

In [5]:
def Model2(img):
    Scale_w1,Range_Real_w1 = prequant(layer_1_data,7)
    Scale_d1,Range_Real_d1 = prequant(img.reshape(1,28,28),7)
    quantized_w1 = quantizefunc(layer_1_data,Range_Real_w1,Scale_w1,0)
    quantized_d1 = quantizefunc(img.reshape(1,28,28),Range_Real_d1,Scale_d1,0)
    
    layer_1_out = relu(conv2d(quantized_w1,quantized_d1))
    layer_1_out = Scale_d1*Scale_w1*pool2d(layer_1_out, (2, 2))
    
    Scale_w2,Range_Real_w2 = prequant(layer_2_data,7)
    Scale_d2,Range_Real_d2 = prequant(layer_1_out,7)
    quantized_w2 = quantizefunc(layer_2_data,Range_Real_w2,Scale_w2,0)
    quantized_d2 = quantizefunc(layer_1_out,Range_Real_d2,Scale_d2,0)
    
    layer_2_out = relu(conv2d(quantized_w2,quantized_d2))
    layer_2_out = Scale_d2*Scale_w2*pool2d(layer_2_out, (2, 2))
    layer_2_out = layer_2_out.transpose(1,2,0) ### ubah format data dari CHW ke WHC
    layer_2_out = layer_2_out.reshape(16*5*5)
    
    Scale_w3,Range_Real_w3 = prequant(layer_3_data,7)
    Scale_d3,Range_Real_d3 = prequant(layer_2_out,7)
    quantized_w3 = quantizefunc(layer_3_data,Range_Real_w3,Scale_w3,0)
    quantized_d3 = quantizefunc(layer_2_out,Range_Real_d3,Scale_d3,0)
    
    layer_3_out = np.matmul(quantized_d3,quantized_w3)
    layer_3_out = Scale_d3*Scale_w3*relu(layer_3_out)
    
    Scale_w4,Range_Real_w4 = prequant(layer_out_data,7)
    Scale_d4,Range_Real_d4 = prequant(layer_3_out,7)
    quantized_w4 = quantizefunc(layer_out_data,Range_Real_w4,Scale_w4,0)
    quantized_d4 = quantizefunc(layer_3_out,Range_Real_d4,Scale_d4,0)
    
    layer_last_out = Scale_d4*Scale_w4*np.matmul(quantized_d4,quantized_w4)
    layer_last_out = softmax(layer_last_out)
    return layer_last_out,

print("line 5 complete")

line 5 complete


# Verifikasi Kuantisasi

Di code ini model yang terkuantisasi dibandingkan akurasinya dengan model yang tidak terkuantisasi berdasarkan akurasi dengan dataset.


In [6]:
print("line 6 started")
val_num_uq = 0
val_num_q = 0
correct_q = np.empty(10000)
correct_uq = np.empty(10000)
val_num_q_2 = 0
correct_q_2 = np.empty(10000)
print("line 6 start loop")
for i in range(10000):    
    if(i % 100 == 0):
        print("loop ", i)
    indata = x_test[i] /255
    label = y_test[i]
    #data = indata.ravel()
    
    keras_res = model.predict_classes(indata.reshape(1,28,28,1))
    res = Model2(indata.reshape(1,28,28))
    
    if(label==keras_res[0]):        
        correct_q[val_num_q] = i
        val_num_q += 1

    if(label==np.argmax(res)):
        correct_uq[val_num_uq] = i
        val_num_uq += 1
        
print('val_num_keras_model :', val_num_q)
print('val_num_quantized_model :', val_num_uq)

print('val val_num_keras_model :', (val_num_q/10000)*100,'%')
print('val quantized  :', (val_num_uq/10000)*100,'%')
print("line 6 complete")

line 6 started
line 6 start loop
loop  0
loop  100
loop  200
loop  300
loop  400
loop  500
loop  600
loop  700
loop  800
loop  900
loop  1000
loop  1100
loop  1200
loop  1300
loop  1400
loop  1500
loop  1600
loop  1700
loop  1800
loop  1900
loop  2000
loop  2100
loop  2200
loop  2300
loop  2400
loop  2500
loop  2600
loop  2700
loop  2800
loop  2900
loop  3000
loop  3100
loop  3200
loop  3300
loop  3400
loop  3500
loop  3600
loop  3700
loop  3800
loop  3900
loop  4000
loop  4100
loop  4200
loop  4300
loop  4400
loop  4500
loop  4600
loop  4700
loop  4800
loop  4900
loop  5000
loop  5100
loop  5200
loop  5300
loop  5400
loop  5500
loop  5600
loop  5700
loop  5800
loop  5900
loop  6000
loop  6100
loop  6200
loop  6300
loop  6400
loop  6500
loop  6600
loop  6700
loop  6800
loop  6900
loop  7000
loop  7100
loop  7200
loop  7300
loop  7400
loop  7500
loop  7600
loop  7700
loop  7800
loop  7900
loop  8000
loop  8100
loop  8200
loop  8300
loop  8400
loop  8500
loop  8600
loop  8700
loop  8800


# Melihat / mengambil weights

In [7]:
print(layer_1_data.shape) #16 filter, 1 filter per channel, size 3x3
print("line 7 complete")

(16, 1, 3, 3)
line 7 complete


In [8]:
print(layer_1_data[0][0]) #weight filter pertama
print("line 8 complete")

[[-0.00843631 -0.06874837  0.11782628]
 [ 0.1014984  -0.11459075  0.10796804]
 [-0.03482499 -0.09923367 -0.03078979]]
line 8 complete
